name: Lint
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  lint:
    runs-on:
      - ubuntu-latest
    container:
      image: python:3.12-bullseye
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install --upgrade poetry
          poetry install --only=test
      - name: Lint
        run: poetry run nox -s lint