name: Publish
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Lint", "Tests"]
    branches: [main]
    types:
      - completed

jobs:
  publish:
    runs-on:
      - ubuntu-latest
    container:
      image: python:3.11-bullseye
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
      - name: Install poetry
        run: |
          pip install --upgrade pip
          pip install --upgrade poetry
      - name: Build
        run: poetry build
      - name: Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
